/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ForTeachersRouteImport } from './routes/for-teachers'
import { Route as ForStudentsRouteImport } from './routes/for-students'
import { Route as ForMathLoversRouteImport } from './routes/for-math-lovers'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForTeachersIndexRouteImport } from './routes/for-teachers.index'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as ForTeachersTgtPgtRouteImport } from './routes/for-teachers.tgt-pgt'
import { Route as ForTeachersCircularFormatsRouteImport } from './routes/for-teachers.circular-formats'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersRoute = ForTeachersRouteImport.update({
  id: '/for-teachers',
  path: '/for-teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStudentsRoute = ForStudentsRouteImport.update({
  id: '/for-students',
  path: '/for-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ForMathLoversRoute = ForMathLoversRouteImport.update({
  id: '/for-math-lovers',
  path: '/for-math-lovers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersIndexRoute = ForTeachersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForTeachersRoute,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersTgtPgtRoute = ForTeachersTgtPgtRouteImport.update({
  id: '/tgt-pgt',
  path: '/tgt-pgt',
  getParentRoute: () => ForTeachersRoute,
} as any)
const ForTeachersCircularFormatsRoute =
  ForTeachersCircularFormatsRouteImport.update({
    id: '/circular-formats',
    path: '/circular-formats',
    getParentRoute: () => ForTeachersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/for-math-lovers': typeof ForMathLoversRoute
  '/for-students': typeof ForStudentsRoute
  '/for-teachers': typeof ForTeachersRouteWithChildren
  '/search': typeof SearchRoute
  '/for-teachers/circular-formats': typeof ForTeachersCircularFormatsRoute
  '/for-teachers/tgt-pgt': typeof ForTeachersTgtPgtRoute
  '/view/$id': typeof ViewIdRoute
  '/for-teachers/': typeof ForTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/for-math-lovers': typeof ForMathLoversRoute
  '/for-students': typeof ForStudentsRoute
  '/search': typeof SearchRoute
  '/for-teachers/circular-formats': typeof ForTeachersCircularFormatsRoute
  '/for-teachers/tgt-pgt': typeof ForTeachersTgtPgtRoute
  '/view/$id': typeof ViewIdRoute
  '/for-teachers': typeof ForTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/for-math-lovers': typeof ForMathLoversRoute
  '/for-students': typeof ForStudentsRoute
  '/for-teachers': typeof ForTeachersRouteWithChildren
  '/search': typeof SearchRoute
  '/for-teachers/circular-formats': typeof ForTeachersCircularFormatsRoute
  '/for-teachers/tgt-pgt': typeof ForTeachersTgtPgtRoute
  '/view/$id': typeof ViewIdRoute
  '/for-teachers/': typeof ForTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/for-math-lovers'
    | '/for-students'
    | '/for-teachers'
    | '/search'
    | '/for-teachers/circular-formats'
    | '/for-teachers/tgt-pgt'
    | '/view/$id'
    | '/for-teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/for-math-lovers'
    | '/for-students'
    | '/search'
    | '/for-teachers/circular-formats'
    | '/for-teachers/tgt-pgt'
    | '/view/$id'
    | '/for-teachers'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/for-math-lovers'
    | '/for-students'
    | '/for-teachers'
    | '/search'
    | '/for-teachers/circular-formats'
    | '/for-teachers/tgt-pgt'
    | '/view/$id'
    | '/for-teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContributeRoute: typeof ContributeRoute
  ForMathLoversRoute: typeof ForMathLoversRoute
  ForStudentsRoute: typeof ForStudentsRoute
  ForTeachersRoute: typeof ForTeachersRouteWithChildren
  SearchRoute: typeof SearchRoute
  ViewIdRoute: typeof ViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers': {
      id: '/for-teachers'
      path: '/for-teachers'
      fullPath: '/for-teachers'
      preLoaderRoute: typeof ForTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-students': {
      id: '/for-students'
      path: '/for-students'
      fullPath: '/for-students'
      preLoaderRoute: typeof ForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-math-lovers': {
      id: '/for-math-lovers'
      path: '/for-math-lovers'
      fullPath: '/for-math-lovers'
      preLoaderRoute: typeof ForMathLoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers/': {
      id: '/for-teachers/'
      path: '/'
      fullPath: '/for-teachers/'
      preLoaderRoute: typeof ForTeachersIndexRouteImport
      parentRoute: typeof ForTeachersRoute
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers/tgt-pgt': {
      id: '/for-teachers/tgt-pgt'
      path: '/tgt-pgt'
      fullPath: '/for-teachers/tgt-pgt'
      preLoaderRoute: typeof ForTeachersTgtPgtRouteImport
      parentRoute: typeof ForTeachersRoute
    }
    '/for-teachers/circular-formats': {
      id: '/for-teachers/circular-formats'
      path: '/circular-formats'
      fullPath: '/for-teachers/circular-formats'
      preLoaderRoute: typeof ForTeachersCircularFormatsRouteImport
      parentRoute: typeof ForTeachersRoute
    }
  }
}

interface ForTeachersRouteChildren {
  ForTeachersCircularFormatsRoute: typeof ForTeachersCircularFormatsRoute
  ForTeachersTgtPgtRoute: typeof ForTeachersTgtPgtRoute
  ForTeachersIndexRoute: typeof ForTeachersIndexRoute
}

const ForTeachersRouteChildren: ForTeachersRouteChildren = {
  ForTeachersCircularFormatsRoute: ForTeachersCircularFormatsRoute,
  ForTeachersTgtPgtRoute: ForTeachersTgtPgtRoute,
  ForTeachersIndexRoute: ForTeachersIndexRoute,
}

const ForTeachersRouteWithChildren = ForTeachersRoute._addFileChildren(
  ForTeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContributeRoute: ContributeRoute,
  ForMathLoversRoute: ForMathLoversRoute,
  ForStudentsRoute: ForStudentsRoute,
  ForTeachersRoute: ForTeachersRouteWithChildren,
  SearchRoute: SearchRoute,
  ViewIdRoute: ViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
